version: '3'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: final1
      MYSQL_USER: final
      MYSQL_PASSWORD: final
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/final1
      - SPRING_DATASOURCE_USERNAME=final
      - SPRING_DATASOURCE_PASSWORD=final
      - SPRING_MAIL_USERNAME=ckdudwn505@gmail.com
      - SPRING_MAIL_PASSWORD=euwfkieuipfcrxty
      - NAVER_CLIENT_ID=Z3F6VrFGz0T7wwsAhEoK
      - NAVER_CLIENT_SECRET=OTz7dGsNip
      - LIBRARY_API_KEY=08ea4c40970006a842b47d0551f5b444f5b91ce547695a16f518a48383a9b1ae
      - LIBRARY_API_FINDBOOKLOCATION_KEY=362c5c7184fc37299dc6f9ae2e879203c6613b0ede5b7f15731eb2b2bc4648be
      - KAKAO_MAP_API_KEY=d996ea46dc69f134d7c0463560f457b8
      - GOOGLE_CLIENT_ID=47411409572-lvbsj0lvuqjel3k787gh9hd63to1p330.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - COOLSMS_API_KEY=NCSVWZZRCCIMLUNW
      - COOLSMS_API_SECRET=R4SZMCVV3YII3YSGYHG8TDFX9JB5YITR
      - COOLSMS_FROM_NUMBER=010-4775-9706
    depends_on:
      - database
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend